services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: loginapp
    tty: true
    volumes:
      - ./loginapp:/var/www/loginapp
    networks:
      - laravel
    working_dir: /var/www/loginapp

  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./loginapp/public:/var/www/loginapp/public
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  db:
    image: mariadb:latest
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: loginapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata: